#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

# Everything lands in the prototype's own gitignored env file, never the repo root.
cd "$(dirname "${BASH_SOURCE[0]}")"
ENV_FILE=".env.local"

banner "WordWell intake adjudication: credentials"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "OpenRouter: prepaid credit, auto-recharge OFF"
say "The pilot budget for the whole of issue #46 is \$10. The protection that"
say "actually matters is prepaid credit with auto-recharge off: a runaway loop"
say "then stops when the credit runs out instead of billing a card."
printf '\n'
open_url "https://openrouter.ai/settings/credits"
step "Sign in, or create an account if you don't have one."
step "Add credit. \$10 is enough for this whole pilot; \$5 is enough for now."
step "Find Auto Top-Up / auto-recharge and make sure it is OFF."
printf '\n'
if ! confirm "Is auto-recharge OFF and the credit added?"; then
  warn "Stopping here. Re-run this script once that's done."
  exit 1
fi

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "OpenRouter: a key scoped to this project"
say "A project-scoped key with its own credit limit, not your account-wide key."
say "If this key leaks or a run misbehaves, the blast radius is its limit."
printf '\n'
open_url "https://openrouter.ai/settings/keys"
step "Click Create Key."
step "Name it:  wordwell-intake-adjudication"
step "Set a credit limit of 10 (dollars). Do not leave the limit blank."
step "Create it, then copy the key. OpenRouter shows it once."
printf '\n'
note "Input is hidden. The key goes straight into $ENV_FILE and is never printed."
ask_secret OPENROUTER_API_KEY "Paste the OpenRouter key:"
if [[ -z "${OPENROUTER_API_KEY:-}" ]]; then
  warn "No key entered. Stopping."
  exit 1
fi
write_env OPENROUTER_API_KEY "$OPENROUTER_API_KEY"
chmod 600 "$ENV_FILE" 2>/dev/null || true

printf '\n'
say "Checking the key and its limit..."
KEY_INFO=$(curl -sS -H "Authorization: Bearer $OPENROUTER_API_KEY" \
  https://openrouter.ai/api/v1/key 2>/dev/null || true)
if [[ -z "$KEY_INFO" ]]; then
  warn "Could not reach OpenRouter to verify the key. Continuing anyway."
elif printf '%s' "$KEY_INFO" | grep -q '"limit":null'; then
  warn "This key has NO credit limit. It can spend the whole account balance."
  confirm "Continue with an unlimited key anyway?" || { warn "Stopping. Set a limit and re-run."; exit 1; }
elif printf '%s' "$KEY_INFO" | grep -q '"error"'; then
  warn "OpenRouter rejected the key. Check you copied all of it, then re-run."
  exit 1
else
  printf '  %s✓%s key accepted, with a credit limit set\n' "$GREEN" "$RESET"
fi
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Choose the model for stage 1"
say "The plan wants a cheap model with structured-output support for the contract"
say "test, and the price recorded. This reads the live catalogue rather than"
say "trusting an identifier written down weeks ago."
printf '\n'
if [[ -d node_modules ]]; then
  npm run --silent models -- 15 2>/dev/null || warn "Could not list models; see https://openrouter.ai/models"
else
  warn "Dependencies not installed yet. Run 'npm install' and re-run this stage,"
  warn "or browse https://openrouter.ai/models and pick one."
fi
printf '\n'
step "Copy one model identifier from the list above, e.g. openai/gpt-5.4-mini."
ask OPENROUTER_MODEL "Model identifier:"
[[ -n "${OPENROUTER_MODEL:-}" ]] && write_env OPENROUTER_MODEL "$OPENROUTER_MODEL"
printf '\n'
say "Now pin the upstream that serves it. This is required: the same model is"
say "served by many upstreams at very different prices, and they do not agree."
printf '\n'
if [[ -d node_modules && -n "${OPENROUTER_MODEL:-}" ]]; then
  npm run --silent models -- "$OPENROUTER_MODEL" 2>/dev/null || warn "Could not list upstreams."
fi
printf '\n'
ask OPENROUTER_PROVIDER "Upstream provider to pin (exact name above):"
if [[ -z "${OPENROUTER_PROVIDER:-}" ]]; then
  warn "No upstream pinned. Runs will refuse to start until one is set in $ENV_FILE."
fi
write_env OPENROUTER_PROVIDER "${OPENROUTER_PROVIDER:-}"
write_env OPENROUTER_TEMPERATURE "0"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Braintrust: experiment tracing"
say "Braintrust records the traces, scores, tokens, cost and latency for each"
say "experiment. The free tier is enough for this pilot."
printf '\n'
open_url "https://www.braintrust.dev/signup"
step "Sign in, or sign up free."
step "Open Settings, then find the API keys section."
note "The exact path moves around; look for 'API keys' under user or org settings."
step "Create a key and copy it."
printf '\n'
ask_secret BRAINTRUST_API_KEY "Paste the Braintrust key:"
if [[ -n "${BRAINTRUST_API_KEY:-}" ]]; then
  write_env BRAINTRUST_API_KEY "$BRAINTRUST_API_KEY"
else
  SKIPPED+=("BRAINTRUST_API_KEY (npm run eval needs it; npm run adjudicate does not)")
  warn "Skipped. 'npm run adjudicate' still works; 'npm run eval' will not."
fi

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Verify, without spending anything"
say "This fetches the live prices, estimates the five-case run, and checks it"
say "against the \$10 cap. It makes no model calls and costs nothing."
printf '\n'
if [[ -d node_modules ]]; then
  npm run --silent adjudicate -- --dry || warn "The dry run failed. The output above says why."
else
  warn "Run 'npm install' first, then: npm run adjudicate -- --dry"
fi
printf '\n'
pause "Press Enter for the summary"

finish
note "$ENV_FILE is gitignored and chmod 600. Never commit it or paste a key into chat."
note "Next:  npm run adjudicate    # the five-case contract test"
